import { type TrezorDevice } from '@suite-common/suite-types';
import { DeviceModelInternal } from '@trezor/device-utils';

import {
    DEMO_DEVICE_ID,
    DEMO_DEVICE_LABEL,
    DEMO_DEVICE_PATH,
    DEMO_DEVICE_STATE,
} from './demoConstants';

export const demoDevice: TrezorDevice = {
    type: 'acquired',
    id: DEMO_DEVICE_ID,
    status: 'available',
    mode: 'normal',
    state: {
        staticSessionId: DEMO_DEVICE_STATE,
    },
    label: DEMO_DEVICE_LABEL,
    // @ts-expect-error - same local-override pattern used by portfolioTrackerDevice
    path: DEMO_DEVICE_PATH,
    firmware: 'valid',
    name: 'Trezor Safe 5',
    features: {
        vendor: 'trezor.io',
        major_version: 2,
        minor_version: 8,
        patch_version: 0,
        bootloader_mode: null,
        device_id: DEMO_DEVICE_ID,
        pin_protection: false,
        passphrase_protection: false,
        language: 'en-US',
        label: DEMO_DEVICE_LABEL,
        initialized: true,
        revision: 'demo0001',
        bootloader_hash: 'demo',
        imported: null,
        unlocked: true,
        firmware_present: null,
        backup_availability: 'NotAvailable',
        flags: 0,
        model: 'T',
        internal_model: DeviceModelInternal.T3T1,
        fw_major: null,
        fw_minor: null,
        fw_patch: null,
        fw_vendor: null,
        unfinished_backup: false,
        no_backup: false,
        recovery_status: 'Nothing',
        capabilities: [],
        backup_type: 'Bip39',
        sd_card_present: false,
        sd_protection: false,
        wipe_code_protection: false,
        session_id: 'demo-session',
        passphrase_always_on_device: false,
        safety_checks: 'Strict',
        auto_lock_delay_ms: 60000,
        display_rotation: 'North',
        experimental_features: false,
    },
    connected: true,
    useEmptyPassphrase: true,
    available: true,
    ts: Date.now(),
    buttonRequests: [],
    metadata: {},
    passwords: {},
    unavailableCapabilities: {},
    availableTranslations: {},
    remember: true,
    authenticityChecks: {
        firmwareRevision: { success: true },
        firmwareHash: { success: true },
    },
};
